"""add station address/website/source and region hq fields

Revision ID: 170d3655b4ca
Revises: 942274709b66
Create Date: 2026-09-29 15:36:12.998731
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '170d3655b4ca'
down_revision: Union[str, None] = '942274709b66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regions', sa.Column('hq_address', sa.String(length=200), nullable=True))
    op.add_column('regions', sa.Column('hq_website', sa.String(length=200), nullable=True))
    op.add_column('stations', sa.Column('address', sa.String(length=200), nullable=True))
    op.add_column('stations', sa.Column('website', sa.String(length=200), nullable=True))
    op.add_column('stations', sa.Column('source', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stations', 'source')
    op.drop_column('stations', 'website')
    op.drop_column('stations', 'address')
    op.drop_column('regions', 'hq_website')
    op.drop_column('regions', 'hq_address')
    # ### end Alembic commands ###
