"""add post category and view_count

Revision ID: 17d3e282c067
Revises: 3f1f81b10630
Create Date: 2026-10-07 22:27:53.985396
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '17d3e282c067'
down_revision: Union[str, None] = '3f1f81b10630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 기존 행이 있는 테이블이라 NOT NULL 컬럼 추가 시 서버 기본값이 필요하다.
    op.add_column(
        'posts',
        sa.Column(
            'category', sa.Enum('info', 'question', 'chat', 'other', name='postcategory', native_enum=False, length=20),
            nullable=False, server_default='chat',
        ),
    )
    op.add_column('posts', sa.Column('view_count', sa.Integer(), nullable=False, server_default='0'))
    op.create_index(op.f('ix_posts_category'), 'posts', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_category'), table_name='posts')
    op.drop_column('posts', 'view_count')
    op.drop_column('posts', 'category')
    # ### end Alembic commands ###
