"""add review and post scraps

Revision ID: 2a4f36ea0ca8
Revises: ea77e41e0d8e
Create Date: 2026-10-07 22:01:42.094029
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2a4f36ea0ca8'
down_revision: Union[str, None] = 'ea77e41e0d8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_scraps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_post_scraps_post_id_posts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_post_scraps_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_scraps')),
    sa.UniqueConstraint('post_id', 'user_id', name=op.f('uq_post_scraps_post_id'))
    )
    op.create_index(op.f('ix_post_scraps_post_id'), 'post_scraps', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_scraps_user_id'), 'post_scraps', ['user_id'], unique=False)
    op.create_table('review_scraps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name=op.f('fk_review_scraps_review_id_reviews')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_review_scraps_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_scraps')),
    sa.UniqueConstraint('review_id', 'user_id', name=op.f('uq_review_scraps_review_id'))
    )
    op.create_index(op.f('ix_review_scraps_review_id'), 'review_scraps', ['review_id'], unique=False)
    op.create_index(op.f('ix_review_scraps_user_id'), 'review_scraps', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_scraps_user_id'), table_name='review_scraps')
    op.drop_index(op.f('ix_review_scraps_review_id'), table_name='review_scraps')
    op.drop_table('review_scraps')
    op.drop_index(op.f('ix_post_scraps_user_id'), table_name='post_scraps')
    op.drop_index(op.f('ix_post_scraps_post_id'), table_name='post_scraps')
    op.drop_table('post_scraps')
    # ### end Alembic commands ###
