"""make post region_id optional

Revision ID: 3109a6cbfded
Revises: 7207f928b18d
Create Date: 2026-10-08 20:05:44.590533
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3109a6cbfded'
down_revision: Union[str, None] = '7207f928b18d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'region_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'region_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
