"""add post score cache column and review station status published index

Revision ID: 4bb88fafcbb3
Revises: 8a04afafbebd
Create Date: 2026-10-08 12:12:16.751497
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4bb88fafcbb3'
down_revision: Union[str, None] = '8a04afafbebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('score', sa.Integer(), server_default='0', nullable=False))
    op.create_index(op.f('ix_posts_score'), 'posts', ['score'], unique=False)
    op.create_index('ix_reviews_station_status_published', 'reviews', ['station_id', 'status', 'published_at'], unique=False)
    # ### end Alembic commands ###

    # 신규 컬럼이라 기존 글은 전부 0으로 채워지므로, 이미 쌓인 post_votes 로 실제 점수를 역산해
    # 채워 넣는다(이후로는 vote_post() 가 매 투표마다 증분 갱신한다).
    op.execute("""
        UPDATE posts SET score = v.score
        FROM (
            SELECT post_id, SUM(CASE WHEN value = 1 THEN 1 WHEN value = -1 THEN -1 ELSE 0 END) AS score
            FROM post_votes GROUP BY post_id
        ) v
        WHERE posts.id = v.post_id
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reviews_station_status_published', table_name='reviews')
    op.drop_index(op.f('ix_posts_score'), table_name='posts')
    op.drop_column('posts', 'score')
    # ### end Alembic commands ###
