"""reviews target stations directly, anonymous authorship

Revision ID: 5aacf5f1053f
Revises: 170d3655b4ca
Create Date: 2026-09-29 15:57:18.425882
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5aacf5f1053f'
down_revision: Union[str, None] = '170d3655b4ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 리뷰가 수사관이 아닌 경찰서를 직접 가리키도록 스키마를 바꾼다. station_id 를 NOT NULL 로
    # 추가해야 하는데 기존 행(전부 출시 전 개발용 샘플 데이터)은 값을 채울 방법이 없으므로 비운다.
    op.execute("DELETE FROM takedown_requests WHERE review_id IS NOT NULL")
    op.execute("DELETE FROM reviews")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('station_id', sa.Integer(), nullable=False))
    op.alter_column('reviews', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reviews', 'case_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('reviews', 'case_number_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_index('ix_reviews_author_id', table_name='reviews')
    op.drop_index('ix_reviews_officer_id', table_name='reviews')
    op.drop_constraint('uq_reviews_author_id', 'reviews', type_='unique')
    op.create_index(op.f('ix_reviews_station_id'), 'reviews', ['station_id'], unique=False)
    op.create_unique_constraint(op.f('uq_reviews_station_id'), 'reviews', ['station_id', 'case_number_hash'])
    op.drop_constraint('fk_reviews_officer_id_officers', 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('fk_reviews_station_id_stations'), 'reviews', 'stations', ['station_id'], ['id'])
    op.drop_column('reviews', 'officer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # 반대 방향도 마찬가지 이유로 되돌리기 전에 비운다.
    op.execute("DELETE FROM takedown_requests WHERE review_id IS NOT NULL")
    op.execute("DELETE FROM reviews")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('officer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_reviews_station_id_stations'), 'reviews', type_='foreignkey')
    op.create_foreign_key('fk_reviews_officer_id_officers', 'reviews', 'officers', ['officer_id'], ['id'])
    op.drop_constraint(op.f('uq_reviews_station_id'), 'reviews', type_='unique')
    op.drop_index(op.f('ix_reviews_station_id'), table_name='reviews')
    op.create_unique_constraint('uq_reviews_author_id', 'reviews', ['author_id', 'officer_id', 'case_number_hash'], postgresql_nulls_not_distinct=False)
    op.create_index('ix_reviews_officer_id', 'reviews', ['officer_id'], unique=False)
    op.create_index('ix_reviews_author_id', 'reviews', ['author_id'], unique=False)
    op.alter_column('reviews', 'case_number_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('reviews', 'case_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('reviews', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('reviews', 'station_id')
    # ### end Alembic commands ###
