"""add station lat/lng for map pins

Revision ID: 5acb95417b8d
Revises: 5aacf5f1053f
Create Date: 2026-10-02 13:48:37.306845
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5acb95417b8d'
down_revision: Union[str, None] = '5aacf5f1053f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stations', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('stations', sa.Column('lng', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stations', 'lng')
    op.drop_column('stations', 'lat')
    # ### end Alembic commands ###
