"""add community features: region follows, post board, review/post comments and votes

Revision ID: 680bdaef8bb6
Revises: 5acb95417b8d
Create Date: 2026-10-07 17:54:29.342310
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '680bdaef8bb6'
down_revision: Union[str, None] = '5acb95417b8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region_follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_region_follows_region_id_regions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_region_follows_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_region_follows')),
    sa.UniqueConstraint('user_id', 'region_id', name=op.f('uq_region_follows_user_id'))
    )
    op.create_index(op.f('ix_region_follows_region_id'), 'region_follows', ['region_id'], unique=False)
    op.create_index(op.f('ix_region_follows_user_id'), 'region_follows', ['user_id'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.String(length=20), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_removed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_posts_author_id_users')),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_posts_region_id_regions')),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('fk_posts_station_id_stations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posts'))
    )
    op.create_index(op.f('ix_posts_author_id'), 'posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_posts_created_at'), 'posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_posts_is_removed'), 'posts', ['is_removed'], unique=False)
    op.create_index(op.f('ix_posts_region_id'), 'posts', ['region_id'], unique=False)
    op.create_index(op.f('ix_posts_station_id'), 'posts', ['station_id'], unique=False)
    op.create_table('post_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_removed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_post_comments_author_id_users')),
    sa.ForeignKeyConstraint(['parent_id'], ['post_comments.id'], name=op.f('fk_post_comments_parent_id_post_comments')),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_post_comments_post_id_posts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_comments'))
    )
    op.create_index(op.f('ix_post_comments_author_id'), 'post_comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_post_comments_parent_id'), 'post_comments', ['parent_id'], unique=False)
    op.create_index(op.f('ix_post_comments_post_id'), 'post_comments', ['post_id'], unique=False)
    op.create_table('post_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('value IN (1, -1)', name=op.f('ck_post_votes_value_updown')),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_post_votes_post_id_posts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_post_votes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_votes')),
    sa.UniqueConstraint('post_id', 'user_id', name=op.f('uq_post_votes_post_id'))
    )
    op.create_index(op.f('ix_post_votes_post_id'), 'post_votes', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_votes_user_id'), 'post_votes', ['user_id'], unique=False)
    op.create_table('review_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_removed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_review_comments_author_id_users')),
    sa.ForeignKeyConstraint(['parent_id'], ['review_comments.id'], name=op.f('fk_review_comments_parent_id_review_comments')),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name=op.f('fk_review_comments_review_id_reviews')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_comments'))
    )
    op.create_index(op.f('ix_review_comments_author_id'), 'review_comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_review_comments_parent_id'), 'review_comments', ['parent_id'], unique=False)
    op.create_index(op.f('ix_review_comments_review_id'), 'review_comments', ['review_id'], unique=False)
    op.create_table('review_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('value IN (1, -1)', name=op.f('ck_review_votes_value_updown')),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name=op.f('fk_review_votes_review_id_reviews')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_review_votes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_votes')),
    sa.UniqueConstraint('review_id', 'user_id', name=op.f('uq_review_votes_review_id'))
    )
    op.create_index(op.f('ix_review_votes_review_id'), 'review_votes', ['review_id'], unique=False)
    op.create_index(op.f('ix_review_votes_user_id'), 'review_votes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_votes_user_id'), table_name='review_votes')
    op.drop_index(op.f('ix_review_votes_review_id'), table_name='review_votes')
    op.drop_table('review_votes')
    op.drop_index(op.f('ix_review_comments_review_id'), table_name='review_comments')
    op.drop_index(op.f('ix_review_comments_parent_id'), table_name='review_comments')
    op.drop_index(op.f('ix_review_comments_author_id'), table_name='review_comments')
    op.drop_table('review_comments')
    op.drop_index(op.f('ix_post_votes_user_id'), table_name='post_votes')
    op.drop_index(op.f('ix_post_votes_post_id'), table_name='post_votes')
    op.drop_table('post_votes')
    op.drop_index(op.f('ix_post_comments_post_id'), table_name='post_comments')
    op.drop_index(op.f('ix_post_comments_parent_id'), table_name='post_comments')
    op.drop_index(op.f('ix_post_comments_author_id'), table_name='post_comments')
    op.drop_table('post_comments')
    op.drop_index(op.f('ix_posts_station_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_region_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_is_removed'), table_name='posts')
    op.drop_index(op.f('ix_posts_created_at'), table_name='posts')
    op.drop_index(op.f('ix_posts_author_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_region_follows_user_id'), table_name='region_follows')
    op.drop_index(op.f('ix_region_follows_region_id'), table_name='region_follows')
    op.drop_table('region_follows')
    # ### end Alembic commands ###
