"""make post author_id nullable for anonymous posting

Revision ID: 7207f928b18d
Revises: 4bb88fafcbb3
Create Date: 2026-10-08 17:36:30.997993
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7207f928b18d'
down_revision: Union[str, None] = '4bb88fafcbb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
