"""add comment removed_at and comment votes

Revision ID: 8a04afafbebd
Revises: 17d3e282c067
Create Date: 2026-10-07 22:43:04.760213
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8a04afafbebd'
down_revision: Union[str, None] = '17d3e282c067'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_comment_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('value IN (1, -1)', name=op.f('ck_post_comment_votes_value_updown')),
    sa.ForeignKeyConstraint(['comment_id'], ['post_comments.id'], name=op.f('fk_post_comment_votes_comment_id_post_comments')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_post_comment_votes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_comment_votes')),
    sa.UniqueConstraint('comment_id', 'user_id', name=op.f('uq_post_comment_votes_comment_id'))
    )
    op.create_index(op.f('ix_post_comment_votes_comment_id'), 'post_comment_votes', ['comment_id'], unique=False)
    op.create_index(op.f('ix_post_comment_votes_user_id'), 'post_comment_votes', ['user_id'], unique=False)
    op.create_table('review_comment_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('value IN (1, -1)', name=op.f('ck_review_comment_votes_value_updown')),
    sa.ForeignKeyConstraint(['comment_id'], ['review_comments.id'], name=op.f('fk_review_comment_votes_comment_id_review_comments')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_review_comment_votes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_comment_votes')),
    sa.UniqueConstraint('comment_id', 'user_id', name=op.f('uq_review_comment_votes_comment_id'))
    )
    op.create_index(op.f('ix_review_comment_votes_comment_id'), 'review_comment_votes', ['comment_id'], unique=False)
    op.create_index(op.f('ix_review_comment_votes_user_id'), 'review_comment_votes', ['user_id'], unique=False)
    op.add_column('post_comments', sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('review_comments', sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review_comments', 'removed_at')
    op.drop_column('post_comments', 'removed_at')
    op.drop_index(op.f('ix_review_comment_votes_user_id'), table_name='review_comment_votes')
    op.drop_index(op.f('ix_review_comment_votes_comment_id'), table_name='review_comment_votes')
    op.drop_table('review_comment_votes')
    op.drop_index(op.f('ix_post_comment_votes_user_id'), table_name='post_comment_votes')
    op.drop_index(op.f('ix_post_comment_votes_comment_id'), table_name='post_comment_votes')
    op.drop_table('post_comment_votes')
    # ### end Alembic commands ###
