"""initial schema

Revision ID: 942274709b66
Revises: 
Create Date: 2026-09-20 19:59:04.178877
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '942274709b66'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_public_statistics')),
    sa.UniqueConstraint('key', 'year', name=op.f('uq_public_statistics_key'))
    )
    op.create_index(op.f('ix_public_statistics_key'), 'public_statistics', ['key'], unique=False)
    op.create_table('regions',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('station_total', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regions'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='userrole', native_enum=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('identity_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_sample', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_stations_region_id_regions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stations')),
    sa.UniqueConstraint('region_id', 'name', name=op.f('uq_stations_region_id'))
    )
    op.create_index(op.f('ix_stations_region_id'), 'stations', ['region_id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('fk_departments_station_id_stations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('station_id', 'name', name=op.f('uq_departments_station_id'))
    )
    op.create_index(op.f('ix_departments_station_id'), 'departments', ['station_id'], unique=False)
    op.create_table('officers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('rank', sa.String(length=30), nullable=False),
    sa.Column('source', sa.Enum('announcement', 'homepage', 'media', 'verified_report', name='officersource', native_enum=False, length=30), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_blinded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_officers_department_id_departments')),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('fk_officers_station_id_stations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_officers'))
    )
    op.create_index(op.f('ix_officers_name'), 'officers', ['name'], unique=False)
    op.create_index(op.f('ix_officers_station_id'), 'officers', ['station_id'], unique=False)
    op.create_table('officer_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['officer_id'], ['officers.id'], name=op.f('fk_officer_assignments_officer_id_officers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_officer_assignments'))
    )
    op.create_index(op.f('ix_officer_assignments_officer_id'), 'officer_assignments', ['officer_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('complainant', 'victim', 'suspect', 'witness', 'lawyer', name='reviewrole', native_enum=False, length=20), nullable=False),
    sa.Column('case_type', sa.Enum('fraud', 'assault', 'cyber', 'sexual', 'traffic', 'other', name='casetype', native_enum=False, length=20), nullable=False),
    sa.Column('case_number', sa.String(length=100), nullable=False),
    sa.Column('case_number_hash', sa.String(length=64), nullable=False),
    sa.Column('fair', sa.SmallInteger(), nullable=True, comment='공정성'),
    sa.Column('proc', sa.SmallInteger(), nullable=True, comment='절차 준수'),
    sa.Column('att', sa.SmallInteger(), nullable=True, comment='조사 태도'),
    sa.Column('comm', sa.SmallInteger(), nullable=True, comment='소통·응대'),
    sa.Column('speed', sa.SmallInteger(), nullable=True, comment='신속성'),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'published', 'rejected', 'blinded', 'removed', name='reviewstatus', native_enum=False, length=20), nullable=False),
    sa.Column('reject_reason', sa.String(length=500), nullable=True),
    sa.Column('blinded_from_status', sa.Enum('pending', 'published', 'rejected', 'blinded', 'removed', name='reviewstatus', native_enum=False, length=20), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('att IS NULL OR att BETWEEN 1 AND 5', name=op.f('ck_reviews_att_range')),
    sa.CheckConstraint('comm IS NULL OR comm BETWEEN 1 AND 5', name=op.f('ck_reviews_comm_range')),
    sa.CheckConstraint('fair IS NULL OR fair BETWEEN 1 AND 5', name=op.f('ck_reviews_fair_range')),
    sa.CheckConstraint('proc IS NULL OR proc BETWEEN 1 AND 5', name=op.f('ck_reviews_proc_range')),
    sa.CheckConstraint('speed IS NULL OR speed BETWEEN 1 AND 5', name=op.f('ck_reviews_speed_range')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_reviews_author_id_users')),
    sa.ForeignKeyConstraint(['officer_id'], ['officers.id'], name=op.f('fk_reviews_officer_id_officers')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_reviews_reviewed_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    sa.UniqueConstraint('author_id', 'officer_id', 'case_number_hash', name=op.f('uq_reviews_author_id'))
    )
    op.create_index(op.f('ix_reviews_author_id'), 'reviews', ['author_id'], unique=False)
    op.create_index(op.f('ix_reviews_officer_id'), 'reviews', ['officer_id'], unique=False)
    op.create_index(op.f('ix_reviews_published_at'), 'reviews', ['published_at'], unique=False)
    op.create_index(op.f('ix_reviews_status'), 'reviews', ['status'], unique=False)
    op.create_table('takedown_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_code', sa.String(length=32), nullable=False),
    sa.Column('target_type', sa.Enum('review', 'officer', name='takedowntarget', native_enum=False, length=20), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.Column('officer_id', sa.Integer(), nullable=True),
    sa.Column('request_type', sa.Enum('delete', 'correct', name='takedowntype', native_enum=False, length=20), nullable=False),
    sa.Column('requester_name', sa.String(length=50), nullable=False),
    sa.Column('requester_contact', sa.String(length=100), nullable=False),
    sa.Column('relation', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'kept', 'removed', name='takedownstatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.CheckConstraint('(review_id IS NOT NULL AND officer_id IS NULL) OR (review_id IS NULL AND officer_id IS NOT NULL)', name=op.f('ck_takedown_requests_exactly_one_target')),
    sa.ForeignKeyConstraint(['officer_id'], ['officers.id'], name=op.f('fk_takedown_requests_officer_id_officers')),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_takedown_requests_resolved_by_users')),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name=op.f('fk_takedown_requests_review_id_reviews')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_takedown_requests'))
    )
    op.create_index(op.f('ix_takedown_requests_officer_id'), 'takedown_requests', ['officer_id'], unique=False)
    op.create_index(op.f('ix_takedown_requests_public_code'), 'takedown_requests', ['public_code'], unique=True)
    op.create_index(op.f('ix_takedown_requests_review_id'), 'takedown_requests', ['review_id'], unique=False)
    op.create_index(op.f('ix_takedown_requests_status'), 'takedown_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_takedown_requests_status'), table_name='takedown_requests')
    op.drop_index(op.f('ix_takedown_requests_review_id'), table_name='takedown_requests')
    op.drop_index(op.f('ix_takedown_requests_public_code'), table_name='takedown_requests')
    op.drop_index(op.f('ix_takedown_requests_officer_id'), table_name='takedown_requests')
    op.drop_table('takedown_requests')
    op.drop_index(op.f('ix_reviews_status'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_published_at'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_officer_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_author_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_officer_assignments_officer_id'), table_name='officer_assignments')
    op.drop_table('officer_assignments')
    op.drop_index(op.f('ix_officers_station_id'), table_name='officers')
    op.drop_index(op.f('ix_officers_name'), table_name='officers')
    op.drop_table('officers')
    op.drop_index(op.f('ix_departments_station_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_stations_region_id'), table_name='stations')
    op.drop_table('stations')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('regions')
    op.drop_index(op.f('ix_public_statistics_key'), table_name='public_statistics')
    op.drop_table('public_statistics')
    # ### end Alembic commands ###
