"""review: 즉시게시 전환 대비 증빙 확인 필드 추가

Revision ID: 95bb8dc166c9
Revises: 680bdaef8bb6
Create Date: 2026-10-07 19:14:54.378784
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '95bb8dc166c9'
down_revision: Union[str, None] = '680bdaef8bb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('evidence_note', sa.String(length=300), nullable=True))
    # 기존 행이 있는 테이블이라 NOT NULL 컬럼 추가 시 서버 기본값이 필요하다(전부 false 로 채움).
    op.add_column('reviews', sa.Column('evidence_verified', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('reviews', sa.Column('evidence_verified_by', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('evidence_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(op.f('fk_reviews_evidence_verified_by_users'), 'reviews', 'users', ['evidence_verified_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reviews_evidence_verified_by_users'), 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'evidence_verified_at')
    op.drop_column('reviews', 'evidence_verified_by')
    op.drop_column('reviews', 'evidence_verified')
    op.drop_column('reviews', 'evidence_note')
    # ### end Alembic commands ###
