"""add officer verification and review replies

Revision ID: ea77e41e0d8e
Revises: 95bb8dc166c9
Create Date: 2026-10-07 21:37:56.978789
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ea77e41e0d8e'
down_revision: Union[str, None] = '95bb8dc166c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('officer_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('rank', sa.String(length=30), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('contact', sa.String(length=200), nullable=False),
    sa.Column('proof_note', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='verificationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reject_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_officer_verifications_reviewed_by_users')),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('fk_officer_verifications_station_id_stations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_officer_verifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_officer_verifications'))
    )
    op.create_index(op.f('ix_officer_verifications_station_id'), 'officer_verifications', ['station_id'], unique=False)
    op.create_index(op.f('ix_officer_verifications_status'), 'officer_verifications', ['status'], unique=False)
    op.create_index(op.f('ix_officer_verifications_user_id'), 'officer_verifications', ['user_id'], unique=False)
    op.create_table('review_replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('show_name', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_review_replies_author_id_users')),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name=op.f('fk_review_replies_review_id_reviews')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_replies')),
    sa.UniqueConstraint('review_id', name=op.f('uq_review_replies_review_id'))
    )
    op.create_index(op.f('ix_review_replies_author_id'), 'review_replies', ['author_id'], unique=False)
    op.create_index(op.f('ix_review_replies_review_id'), 'review_replies', ['review_id'], unique=False)
    op.add_column('users', sa.Column('officer_station_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('officer_name', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('officer_rank', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('officer_department', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('officer_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(op.f('fk_users_officer_station_id_stations'), 'users', 'stations', ['officer_station_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_officer_station_id_stations'), 'users', type_='foreignkey')
    op.drop_column('users', 'officer_verified_at')
    op.drop_column('users', 'officer_department')
    op.drop_column('users', 'officer_rank')
    op.drop_column('users', 'officer_name')
    op.drop_column('users', 'officer_station_id')
    op.drop_index(op.f('ix_review_replies_review_id'), table_name='review_replies')
    op.drop_index(op.f('ix_review_replies_author_id'), table_name='review_replies')
    op.drop_table('review_replies')
    op.drop_index(op.f('ix_officer_verifications_user_id'), table_name='officer_verifications')
    op.drop_index(op.f('ix_officer_verifications_status'), table_name='officer_verifications')
    op.drop_index(op.f('ix_officer_verifications_station_id'), table_name='officer_verifications')
    op.drop_table('officer_verifications')
    # ### end Alembic commands ###
