"""make comment author_id optional for anonymous comments

Revision ID: f09de2cc789d
Revises: 3109a6cbfded
Create Date: 2026-10-08 22:29:20.396254
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f09de2cc789d'
down_revision: Union[str, None] = '3109a6cbfded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post_comments', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('review_comments', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review_comments', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('post_comments', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
